version: '3.8'

services:
  backend:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - app/.env
    volumes:
      - ./app:/app/app

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules

  db:
    image: postgres:13
    env_file:
      - app/.env
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: